# Generated by Django 5.2 on 2025-06-09 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_avaliacao_avaliacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avaliacao',
        ),
    ]
