# Generated by Django 5.2 on 2025-05-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.TextField(max_length=100)),
                ('senha', models.TextField(max_length=30)),
            ],
        ),
    ]
